### ISSUE TITLE
Keychain key and name should be configurable

### ISSUE THREAD

**Issue by pedromcunha** [PROPSProject/props-kit-ios#1]
Currently there are places in the app which reference the TOTPSeed key in the keychain.

A third party pod could potentially access the TOPT stored on the keychain. I would recommend that the key be configurable by the client using the SDK, to ensure another layer of security.

https://github.com/PROPSProject/props-kit-ios/blob/96424870455723b1980844e5df272266cec8f67c/PropsKit/Keychain.swift#L28

**Comment by ptrwtts** [comment]
If we prefix the key with the wallet address, as planned (#7), it should prevent malicious 3rd parties from phishing for wallet info (they need to know what wallet they are looking for).
